---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we’ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term “efficiency” means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Your essay should address the following questions:

-   What is the definition of “efficiency”?

-   What does efficiency look like in statistical computing / data science?

-   What does efficiency allow you to do?

-   Why is efficiency important?

-   Where did you encounter efficiency, and what were some [“a-ha” moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

Efficiency in statistical computing and data science is about maximizing productivity while minimizing wasted time and resources—like using the inside most lane in a track race. The code looks clean and concise which accomplishes tasks quickly. This is done by carefully selecting packages like dplyr instead trying to use the one that you know in every situation. Although we didn't encounter huge datasets in class much, efficiency would allow us to handle larger datasets and focus on the analysis rather than inefficiencies in our code. After all, the whole idea of data science is to get insights from data as effectively as possible.\
\
Lab 8 really is the king of efficiency aha moments. We were asked to revisit some code from previous labs, and then make them more efficient, I don't have a good example from Lab 8 in my portfolio to share. However, Lab 5 using joins opened a new world for me. Instead of using str_detect() or !str_detect() I could join datasets together. Now, I didnt have to manually look over them and match id's and such, the functions already did that (joins from WD-5 and WD-6). Another moment came in Lab 5 when I used summarize() with across() and then pivot_longer to make the data readable. Sure the table wasn't award winning caliber but it efficiently gave me the insights I needed.
